version: '3'

tasks:
  test:
    desc: "Run all tests and generate a coverage report"
    cmds:
      - go test -v -coverprofile=coverage.out ./...

  build:
    desc: "Build the project"
    cmds:
      - go build -v ./...
